using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks.Sources;

namespace Bipolar.EventSerialization.SourceGeneration
{
    [Generator]
    internal sealed class SerializedEventSubscriberGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new MembersWithAttributesSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not MembersWithAttributesSyntaxReceiver receiver)
                return;

            var debugCode = $"public partial class GeneratedMembers\n {{ \npublic int Count = {receiver.Candidates.Count};\n";

            var serializedEventsByContaingClass = new Dictionary<INamedTypeSymbol, List<ISymbol>>(SymbolEqualityComparer.Default);
            for (int i = 0; i < receiver.Candidates.Count; i++)
            {
                var candidateSyntax = receiver.Candidates[i];

                var model = context.Compilation.GetSemanticModel(candidateSyntax.SyntaxTree);

                IEnumerable<SyntaxNode> symbolNodes = candidateSyntax switch
                {
                    FieldDeclarationSyntax field => field.Declaration.Variables,
                    EventFieldDeclarationSyntax eventField => eventField.Declaration.Variables,
                    _ => new[] { (SyntaxNode)candidateSyntax }
                };

                foreach (var symbolNode in symbolNodes)
                {
                    var symbol = model.GetDeclaredSymbol(symbolNode);
                    debugCode += $"public string Candidate{i} = @\"{symbol}\";\n";

                    if (symbol is null)
                        continue;

                    var containingClass = symbol.ContainingType;
                    if (containingClass is null)
                        continue;

                    if (Utility.HasSerializeEventAttribute(symbol) == false)
                        continue;

                    if (Utility.IsVoidDelegate(symbol) == false)
                        continue;

                    if (serializedEventsByContaingClass.TryGetValue(containingClass, out var eventsList) == false)
                    {
                        serializedEventsByContaingClass[containingClass] = eventsList = [];
                    }
                    eventsList.Add(symbol);
                }
            }

            debugCode += "}\n";
            //context.AddSource("nowy_plik.g.cs", debugCode);

            foreach (var kvp in serializedEventsByContaingClass)
            {
                GenerateSource(context, kvp.Key, kvp.Value);
            }
        }

        private void GenerateSource<TList>(GeneratorExecutionContext context, INamedTypeSymbol classSymbol, TList members)
            where TList : IList<ISymbol>
        {
            var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : classSymbol.ContainingNamespace.ToDisplayString();

            var accessModifier = classSymbol.DeclaredAccessibility.ToString().ToLower();
            var className = classSymbol.Name;
            var subscriberClassName = namespaceName is not null
                ? $"{namespaceName}_{className}_SerializeEventSubscriber"
                : $"{className}_SerializeEventSubscriber";

            var textWriter = new StringWriter();
            var codeWriter = new IndentedTextWriter(textWriter);
            codeWriter.WriteLine("// <auto-generated/>");
            codeWriter.WriteLine();
            codeWriter.WriteLine("using UnityEngine;");
            codeWriter.WriteLine("using UnityEngine.Events;");
            codeWriter.WriteLine();

            if (namespaceName is not null)
            {
                codeWriter.WriteLine($"namespace {namespaceName}");
                codeWriter.WriteLine("{");
                codeWriter.Indent++;
            }

            WritePartialClassWithUnityEvents();
            WriteSubscriberClass();

            if (namespaceName is not null)
            {
                codeWriter.Indent--;
                codeWriter.WriteLine("}");
            }

            string sourceContent = textWriter.ToString();

            context.AddSource(subscriberClassName + ".g.cs", sourceContent);

            void WritePartialClassWithUnityEvents() 
            {
                codeWriter.WriteLine($"[RequireComponent(typeof({subscriberClassName}))]");
                codeWriter.WriteLine($"{accessModifier} partial class {className}");
                codeWriter.WriteLine("{");
                codeWriter.Indent++;

                codeWriter.WriteLine("[Space]");
                for (int i = 0; i < members.Count; i++)
                {
                    var eventSymbol = members[i];
                    var eventName = eventSymbol.Name;
                    codeWriter.WriteLine("[SerializeField]");

                    var parameters = Utility.GetDelegateParameters(eventSymbol);
                    if (parameters.IsEmpty)
                    {
                        codeWriter.Write($"private UnityEvent");
                    }
                    else
                    {
                        int argsCount = Math.Min(4, parameters.Length);
                        var typeArgs = string.Join(", ", parameters.Take(argsCount).Select(p => p.Type.ToDisplayString()));
                        codeWriter.Write($"private UnityEvent<{typeArgs}>");
                    }
                    codeWriter.WriteLine($" _{eventName}Event;");
                }

                codeWriter.Indent--;
                codeWriter.WriteLine("}");
            }

            void WriteSubscriberClass()
            {
                codeWriter.WriteLine();
                codeWriter.WriteLine($"internal class {subscriberClassName} : MonoBehaviour");
                codeWriter.WriteLine("{");
                codeWriter.Indent++;
                codeWriter.Indent--;
                codeWriter.WriteLine("}");
            }
        }
    }

    internal sealed class MembersWithAttributesSyntaxReceiver : ISyntaxReceiver
    {
        public List<MemberDeclarationSyntax> Candidates { get; } = new List<MemberDeclarationSyntax>();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is not MemberDeclarationSyntax member)
                return;

            // Quick pre-filter: only bother with members that have at least one attribute.
            if (member.AttributeLists.Any() == false)
                return;

            if (member is FieldDeclarationSyntax
                       or PropertyDeclarationSyntax
                       or EventDeclarationSyntax
                       or EventFieldDeclarationSyntax)
            {
                Candidates.Add(member);
            }
        }
    }
}
